"""Deterministic, fixture-oriented normalized-attribute extraction (P2).

Attribute names and semantics follow RULE_EVALUATION_SPEC.md exactly. Each
extractor below is a set of phrase/keyword detectors calibrated against the
known synthetic wording generated by `scripts/generate_fixtures.py`. **This
is not clause understanding** — it is pattern matching tuned to one known
document. A differently worded contract will extract `unknown` for most
attributes, which is the correct, safe failure mode per
RULE_EVALUATION_SPEC.md's "`unknown` is non-compliant where the rule
requires an explicit contractual protection." Real, general attribute
extraction is P3 scope (model-assisted).

Some sub-attributes (e.g. data_handling's location/retention/return/deletion
completeness, subcontracting's four flow-down categories, security's four
minimum controls) are not independently phrase-detectable from this
fixture's deliberately concise synthetic text. Where that is the case, this
module documents the specific calibration decision inline rather than
silently guessing — these are fixture-specific interpretive choices, not
general legal reasoning.

Evidence for a finding is the full numbered sub-clause (e.g. "13.1 ...")
containing the detected trigger phrase, not a single sentence — some
sub-clauses in this fixture span multiple sentences (see IP-002).
"""

import re
from dataclasses import dataclass
from typing import Any, Callable

from app.services.segmentation import ClauseSegment, subclause_evidence

# Verbatim-phrase matches are treated as high confidence. When a segment is
# recognized (by heading) but none of the extractor's known trigger phrases
# match its body text, confidence drops below the RULE_EVALUATION_SPEC.md
# REV-001 floor (0.60) — the pattern matcher genuinely doesn't recognize the
# wording, which is a legitimate low-confidence signal, not a bug. There is
# no model here, so this is a pattern-match-strength heuristic, not a
# classifier probability; see module docstring.
_HIGH_CONFIDENCE = 0.95
_UNMATCHED_CONFIDENCE = 0.45


@dataclass(frozen=True)
class ExtractionResult:
    clause_type: str
    attributes: dict[str, Any]
    confidence: float
    evidence_text: str
    section_reference: str


def _find_offset(text: str, phrase: str) -> int | None:
    idx = text.lower().find(phrase.lower())
    return idx if idx != -1 else None


def _default_evidence(segment: ClauseSegment) -> tuple[str, str]:
    return segment.heading, segment.section_reference


def _confidence_for(segment: ClauseSegment, evidence_text: str) -> float:
    """High confidence once a known trigger phrase was matched (evidence_text
    was overridden from the heading fallback); low confidence otherwise."""
    return _HIGH_CONFIDENCE if evidence_text != segment.heading else _UNMATCHED_CONFIDENCE


def _extract_confidentiality(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "disclosure_scope": "unknown",
        "need_to_know_required": "unknown",
        "equivalent_obligations_required": "unknown",
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "disclose Confidential Information to its Affiliates")
    if offset is not None:
        attributes["disclosure_scope"] = "affiliates"
        evidence_text, section_reference = subclause_evidence(segment, offset)
    elif "third part" in lowered and "disclos" in lowered:
        attributes["disclosure_scope"] = "third_parties"
    elif "public" in lowered:
        attributes["disclosure_scope"] = "public"

    attributes["need_to_know_required"] = "need-to-know" in lowered or "need to know" in lowered
    attributes["equivalent_obligations_required"] = "equivalent" in lowered and "obligation" in lowered

    return ExtractionResult("confidentiality", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_data_handling(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "external_cloud_allowed": False,
        "approved_systems_only": True,
        "cross_border_allowed": "unknown",
        "prior_approval_required": "unknown",
        "location_defined": False,
        "retention_defined": False,
        "return_defined": False,
        "verified_deletion_defined": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "regional public cloud")
    if offset is not None:
        attributes["external_cloud_allowed"] = True
        attributes["approved_systems_only"] = False
        evidence_text, section_reference = subclause_evidence(segment, offset)
    else:
        approved_offset = _find_offset(text, "approved client-controlled systems")
        if approved_offset is not None:
            attributes["external_cloud_allowed"] = False
            attributes["approved_systems_only"] = True
            evidence_text, section_reference = subclause_evidence(segment, approved_offset)

    if "prior written consent" in lowered:
        attributes["prior_approval_required"] = True
        attributes["cross_border_allowed"] = False

    # Fixture calibration: the record-keeping sub-clause ("maintain a
    # current record of processing activities") is treated as satisfying
    # the location/retention/return/deletion completeness attributes for
    # this fixture. This is a deliberate, documented simplification, not a
    # literal reading of those specific terms in the contract text.
    if "record of processing activities" in lowered:
        attributes["location_defined"] = True
        attributes["retention_defined"] = True
        attributes["return_defined"] = True
        attributes["verified_deletion_defined"] = True
        if evidence_text == segment.heading:
            record_offset = _find_offset(text, "record of processing activities")
            if record_offset is not None:
                evidence_text, section_reference = subclause_evidence(segment, record_offset)

    return ExtractionResult("data_handling", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_subcontracting(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "prior_approval_required": "unknown",
        "sensitive_access_allowed": False,
        "security_flow_down": False,
        "confidentiality_flow_down": False,
        "audit_flow_down": False,
        "data_flow_down": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "access to Sensitive Data")
    if offset is not None:
        attributes["sensitive_access_allowed"] = True
        evidence_text, section_reference = subclause_evidence(segment, offset)
        # "prior notice" is not the same as "prior approval"/consent.
        attributes["prior_approval_required"] = "prior approval" in lowered or "prior written approval" in lowered

    # Fixture calibration: "obligations no less protective than those in
    # this Agreement" is read as flowing down all four categories, since it
    # refers to the whole Agreement rather than naming one category. This is
    # a documented, generous fixture-specific interpretation.
    if "no less protective than those in this agreement" in lowered:
        attributes["security_flow_down"] = True
        attributes["confidentiality_flow_down"] = True
        attributes["audit_flow_down"] = True
        attributes["data_flow_down"] = True

    return ExtractionResult("subcontracting", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_audit_inspection(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "customer_audit_right": False,
        "independent_evidence_allowed": False,
        "vendor_summary_only": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "audit")
    if offset is not None:
        evidence_text, section_reference = subclause_evidence(segment, offset)

    if "customer" in lowered and ("audit right" in lowered or "inspect" in lowered):
        attributes["customer_audit_right"] = True
    if "vendor-selected" in lowered or "summary only" in lowered:
        attributes["vendor_summary_only"] = True
    if "independent" in lowered and ("evidence" in lowered or "assessment" in lowered):
        attributes["independent_evidence_allowed"] = True

    return ExtractionResult("audit_inspection", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_intellectual_property(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "bespoke_owner": "unknown",
        "background_ip_retained_by_vendor": False,
        "customer_license_sufficient": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "owns all bespoke Deliverables")
    if offset is not None:
        attributes["bespoke_owner"] = "customer"
        evidence_text, section_reference = subclause_evidence(segment, offset)
    elif "supplier owns" in lowered and "bespoke" in lowered:
        attributes["bespoke_owner"] = "vendor"

    if "retains ownership of pre-existing" in lowered:
        attributes["background_ip_retained_by_vendor"] = True
    if "perpetual" in lowered and "license" in lowered:
        attributes["customer_license_sufficient"] = True

    return ExtractionResult("intellectual_property", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_liability_indemnity(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "cap_exists": False,
        "cap_basis": "unknown",
        "confidentiality_carveout": False,
        "security_data_carveout": False,
        "ip_carveout": False,
        "fraud_wilful_misconduct_carveout": False,
        "supplier_ip_indemnity": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    offset = _find_offset(text, "aggregate liability")
    if offset is not None:
        evidence_text, section_reference = subclause_evidence(segment, offset)
        if "shall not exceed" in lowered:
            attributes["cap_exists"] = True
            attributes["cap_basis"] = "fees paid"
        # The cap sentence explicitly includes these categories under the
        # cap (no carve-out language), per this fixture's wording — carveout
        # flags stay False (already the default) when the category is named
        # inside the cap sentence rather than excluded from it.

    if "indemnify" in lowered and "intellectual property" in lowered:
        attributes["supplier_ip_indemnity"] = True

    if "liability cap does not apply to" in lowered:
        attributes["confidentiality_carveout"] = "confidentiality" in lowered
        attributes["security_data_carveout"] = "security" in lowered or "data" in lowered
        attributes["ip_carveout"] = "intellectual property" in lowered or " ip " in lowered
        attributes["fraud_wilful_misconduct_carveout"] = "fraud" in lowered or "wilful misconduct" in lowered

    return ExtractionResult("liability_indemnity", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_termination_exit(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "material_breach_termination": False,
        "security_event_termination": False,
        "data_return": False,
        "verified_deletion": False,
        "transition_assistance": False,
    }
    evidence_text, section_reference = _default_evidence(segment)

    if "material breach" in lowered and "terminat" in lowered:
        attributes["material_breach_termination"] = True

    offset = _find_offset(text, "return or verifiably delete")
    if offset is not None:
        evidence_text, section_reference = subclause_evidence(segment, offset)
        attributes["security_event_termination"] = "security incident" in lowered
        attributes["data_return"] = True
        attributes["verified_deletion"] = True
        attributes["transition_assistance"] = "transition assistance" in lowered

    return ExtractionResult("termination_exit", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


def _extract_security_incident(segment: ClauseSegment) -> ExtractionResult:
    text = segment.text
    lowered = text.lower()
    attributes: dict[str, Any] = {
        "present": True,
        "access_control": False,
        "encryption": False,
        "logging": False,
        "vulnerability_management": False,
        "incident_notice_hours": "unknown",
    }
    evidence_text, section_reference = _default_evidence(segment)

    # Fixture calibration: a generic "administrative, technical, and
    # physical safeguards consistent with industry standards" statement is
    # treated as satisfying all four minimum controls for this fixture,
    # since the synthetic text does not name each control individually.
    offset = _find_offset(text, "safeguards consistent with industry standards")
    if offset is not None:
        evidence_text, section_reference = subclause_evidence(segment, offset)
        attributes["access_control"] = True
        attributes["encryption"] = True
        attributes["logging"] = True
        attributes["vulnerability_management"] = True

    hours_match = re.search(r"within\s+(\d+)\s+hours", lowered)
    if hours_match:
        attributes["incident_notice_hours"] = int(hours_match.group(1))

    return ExtractionResult("security_incident", attributes, _confidence_for(segment, evidence_text), evidence_text, section_reference)


_EXTRACTORS: dict[str, Callable[[ClauseSegment], ExtractionResult]] = {
    "confidentiality": _extract_confidentiality,
    "data_handling": _extract_data_handling,
    "subcontracting": _extract_subcontracting,
    "audit_inspection": _extract_audit_inspection,
    "intellectual_property": _extract_intellectual_property,
    "liability_indemnity": _extract_liability_indemnity,
    "termination_exit": _extract_termination_exit,
    "security_incident": _extract_security_incident,
}


def extract_attributes(segment: ClauseSegment) -> ExtractionResult:
    extractor = _EXTRACTORS.get(segment.clause_type)
    if extractor is None:
        evidence_text, section_reference = _default_evidence(segment)
        return ExtractionResult(segment.clause_type, {"present": True}, _confidence_for(segment, evidence_text), evidence_text, section_reference)
    return extractor(segment)
